### ISSUE TITLE
Do clausal subjects need to be distinguished from non-clausal subjects

### ISSUE THREAD

**Issue by ftyers** [ftyers/docs#6]
So far we have not been distinguishing non-clausal subjects from clausal subjects. This is because the distinction is trivially recoverable from the morphology. If the subject is a verb, it is clausal, if not it is nominal. 

```
Мүсін жасау , жартастарға рельеф қашау елеулі орын алды . 
making sculptures , cliffs-to reliefs carving important place took .
```

Here we mark "қашау" as just "subj" although it is technically a clause. The fact that it is a clause can be explained by the morphology. The POS is verbal.

The example:

```
Сен ол өтірікші .
You it liar . 
```

Seems like it is missing something, or is not clausal, e.g. if it were:

```
Сен ол — өтірікші . 
```

That is:

```
Сен ол _ — өтірікші _ . 
```

Then we would probably analyse it as:

   subj(ол, Сен)
   cop(ол, _)
   punct(ол, —)
   subj(өтірікші, ол)
   cop(өтірікші, _)

Admittedly we have here a "clausal subject" with no verb. But I'm not sure what advantage this gives ?

**Comment by makazhan** [comment]
I understand that this approach reduces ambiguity, but in most cases it's easy to tell clausal subjects from nominal ones. So why not to annotate? I too cannot tell what advantage we get from discriminating those two. I just see it as being for the sake of consistency both within the language (we do have ccomp, acl, advcl) and cross-linguistically (maybe in some languages the difference is important).

Regarding the _liar_ example, I initially did not consider it clausal. I thought of it when searching for evidence of expletives (existential _it_). Indeed, _ол_ does not have its usual meaning here if anything it is used for emphasis that someone was herself a liar in spite of accusing others. Compare:

```
Біз гол соқтық - We scored the goal
vs
Біз ол гол соққан - We [and not someone else] scored the goal = 
= *We* were the ones who scored the goal
```

However, syntactically _ол_ seems to be a predicate, so I opted for `nsubj(Сен,ол)>csubj(ол,өтірікші)` [the order is (dep,gov)]

There are other examples of `csubj` with non-verbal predicates:

```
1 атасы grand-father.3SG 2 nsubj
2 басқа other            4 csubj
3 аттан horse.ABL        4 iobj
4 түс   descent          0 root
```

**Comment by jonorthwash** [comment]
I'm inclined to agree with your point about consistency.  We're already treating verb phrases differently when they act like substantives, attributives, and adverbials, so we might as well treat them differently as substantive subjects too.

**Comment by jonorthwash** [comment]
In terms of "Біз ол гол соққан", can you say "Біз ол гол соқтық" or "Біз ол гол соғамыз" (using the same construction, not in the meaning of using ол as a determiner for гол)?

My intuition is that this is more like an appositive construction of some sort, so you need something attributive or substantive (e.g., a verbal noun or adjective, like соққан, соғатын, or соғар—or just a noun or adjective, like өтірікші), but you can't have a finite verb (like соқтық, соғамыз, etc.).  (I would also opt to put a comma after ол in all of these examples.  It seems like it could get confusing without a comma since ол can also be a determiner, but I'm not familiar with the relevant standard in Kazakh.)

Anyway, I'm not a native speaker of Kazakh, so my intuitions on this could very well be wrong.  What do you think?

**Comment by ftyers** [comment]
Ok, I think we can close this discussion as done with the resolution that we should distinguish clausal subjects from nominal subjects using `csubj` and `nsubj`. The remaining question should be reopened in a new post. Documentation updates at: https://github.com/ftyers/docs/blob/pages-source/_kk-dep/csubj.md

**Comment by jonorthwash** [comment]
The other discussion has been opened as a [new issue](https://github.com/ftyers/docs/issues/7).
