### ISSUE TITLE
Use of language-specific relation nmod:poss

### ISSUE THREAD

**Issue by ftyers** [ftyers/docs#9]
AM uses `nmod:poss` relation for genitives, where FMT+JNW use `nmod` with no subrelation.

As there are no adverbial uses of genitive, when `nmod` is with genitive then we can assume it gets the `nmod:poss` relation. I don't mind either way, it would be fairly easy to implement a script to just relabel `nmod` with `nmod:poss` if the noun is in genitive. 

What do other people think ?

**Comment by jonorthwash** [comment]
Either way makes sense to me.  Redundancy never hurts, but what do the UD guidelines say?  What about the UD devs?

**Comment by ftyers** [comment]
The UD guidelines do not mandate the use of `nmod:poss`, but it is widely used (e.g. in Finnish, Spanish, English, French and others).[1]
1. http://universaldependencies.github.io/docs/ext-dep-index.html

**Comment by jonorthwash** [comment]
The relationship between genitive nominals (definite or indefinite) and the "possessed" nominal is pretty strict in Turkic languages that obligatorily mark the latter (which includes Kazakh).  Since we use `nmod` for so many things, it probably wouldn't hurt to have `nmod:poss` to distinguish this type of relation (even though the specific relation is easily recoverable from the morphology, or even just POS—if either is annotated).

Alternatively, could we make `nmod:poss` the default, but optionally allow `nmod`, or something of that sort?

**Comment by ftyers** [comment]
I think I'm happy with just saying `nmod:poss` for genitive nominals modifying other nominals. We can retrieve the previous analysis by collapsing them in any case.
